# GIA-Re 전역 설정 파일
# - 이 파일의 값은 파이프라인 전역에서 공유됩니다.
# - 값 변경 후 재실행하면 즉시 반영됩니다.
# - 필요 시 환경별 파일(config/settings.production.yaml 등)로 오버라이드하세요.

api:
  timeout: 180        # 초 단위 요청 타임아웃(서버 응답을 기다리는 최대 시간)
  max_retries: 2     # 일시적 오류 발생 시 재시도 횟수(클라이언트 레벨에서 제어)
  base_url: null     # OpenAI 호환 API 엔드포인트(URL). null이면 기본(OpenAI 공식)
  # api_key: ""     # (권장) 환경변수로 설정: OPENAI_API_KEY
  # org_id: ""      # (선택) 조직 ID가 필요한 환경에서 사용
  # project: ""     # (선택) 프로젝트 라우팅이 필요한 환경에서 사용

models:
  # 파이프라인 단계별 기본 모델명. 값이 비어있으면 default가 사용됩니다.
  default: "gpt-5-mini-2025-08-07"                 # 명시되지 않은 용도 기본 모델(경량)
  paraphrase: "gpt-5-mini-2025-08-07"              # 질문 표면변형/리라이팅 단계(경량)
  question_generation: "gpt-5-mini-2025-08-07"     # 규칙/LLM 질문 생성(속도/비용 우선)
  intent_parsing: "gpt-5-mini-2025-08-07"          # 의도/카테고리 추출(경량)
  hypothesis_review: "gpt-5-mini-2025-08-07"            # 고품질 리뷰/검토(정밀)
  answer_synthesis: "gpt-5-mini-2025-08-07"        # 최종 답변 합성/정리(경량)
  enhanced_generation: "gpt-5-mini-2025-08-07"          # 고도화 생성(복합 추론, 정밀)

features:
  use_intent_llm: true   # true: 의도 분석에 LLM 사용, false: 규칙 기반 우선
  enable_llm_review: true # true: LLM 리뷰 단계 활성화(품질 점검)
  disable_hypo_review: false # true: 가설 리뷰 단계를 완전히 비활성화(바이패스)

generation:
  basic_questions_per_category: 30    # 카테고리별 규칙 기반(베이직) 질문 생성 수
  enhanced_questions_per_category: 120  # 카테고리별 고도화 LLM 질문 생성 수 (100개 이상 보장)

logging:
  level: "INFO"   # 로그 레벨(DEBUG/INFO/WARNING/ERROR)
  format: "%(asctime)s - %(levelname)s - %(message)s"  # 로그 출력 포맷
